version: "2"

services:
  mrs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18090:18090"
    volumes:
      - "/srv/data:/srv/mrs-data/raw"
      - "/srv/mrs:/srv/mrs-data/mrs"
    command: mrs server start -p /var/run/mrs.pid --no-daemon
